name: 기능 요청
description: 새로운 기능이나 개선 사항을 제안해주세요!
title: "[기능] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        기능 요청을 제안해주셔서 감사합니다! 아래 정보를 작성해주시면 더 나은 제품을 만드는 데 도움이 됩니다.

  - type: textarea
    id: problem
    attributes:
      label: 문제점 또는 개선이 필요한 부분
      description: 이 기능이 해결하거나 개선할 문제점을 설명해주세요.
      placeholder: 예: 현재 JavaScript 코드를 실행할 때 결과를 복사하는 기능이 없어서 불편합니다.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 제안하는 해결 방법
      description: 원하는 기능이나 개선 사항을 구체적으로 설명해주세요.
      placeholder: 예: 실행 결과 옆에 복사 버튼을 추가하여 클릭 한 번으로 결과를 클립보드에 복사할 수 있도록 하고 싶습니다.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 대안
      description: 고려했던 다른 해결 방법이나 대안이 있다면 작성해주세요. (선택사항)
      placeholder: 예: 키보드 단축키(Cmd+C)로 결과를 복사하는 방법도 고려했습니다.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 이 기능의 중요도를 선택해주세요.
      options:
        - 낮음 - 편의 기능이지만 없어도 괜찮음
        - 보통 - 유용하지만 급하지 않음
        - 높음 - 중요한 기능이지만 필수는 아님
        - 매우 높음 - 필수적이거나 핵심 기능
    validations:
      required: false

  - type: checkboxes
    id: areas
    attributes:
      label: 관련 영역
      description: 이 기능이 영향을 미치는 영역을 선택해주세요. (복수 선택 가능)
      options:
        - label: 프론트엔드 (UI/UX)
        - label: 백엔드 (Rust/Tauri)
        - label: JavaScript 런타임
        - label: 코드 에디터
        - label: 실행 결과 표시
        - label: 파일 관리
        - label: 설정/환경
        - label: 성능
        - label: 문서화
        - label: 기타
    validations:
      required: false

  - type: textarea
    id: use_cases
    attributes:
      label: 사용 사례
      description: 이 기능이 어떻게 사용될지 구체적인 시나리오를 작성해주세요. (선택사항)
      placeholder: |
        예시:
        1. 사용자가 JavaScript 코드를 실행합니다
        2. 실행 결과가 표시됩니다
        3. 사용자가 복사 버튼을 클릭합니다
        4. 결과가 클립보드에 복사됩니다
      render: markdown
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: 목업/스크린샷
      description: UI 변경이 포함된 경우, 목업이나 스크린샷을 공유해주세요. (선택사항)
      placeholder: 목업 이미지를 드래그 앤 드롭하거나 붙여넣으세요.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 기능 요청과 관련된 추가 정보나 참고 자료가 있다면 작성해주세요. (선택사항)
      placeholder: 예: 유사한 기능을 제공하는 다른 도구의 예시나 참고할 만한 자료가 있습니다.
    validations:
      required: false

