name: Rust Test

on:
  push:
    branches: [main]
    paths:
      - "apps/executeJS/src-tauri/**"
      - "crates/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/rust-test.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/executeJS/src-tauri/**"
      - "crates/**"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  rust-test:
    name: Rust Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libglib2.0-dev \
            pkg-config

      - name: Run Rust tests
        run: cargo test --all-targets
