name: Rust Lint

on:
  push:
    branches: [main]
    paths:
      - "apps/executeJS/src-tauri/**"
      - "crates/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rustfmt.toml"
      - ".github/workflows/rust-lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/executeJS/src-tauri/**"
      - "crates/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rustfmt.toml"

jobs:
  rust-lint:
    name: Rust Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          cache: true
          matcher: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libglib2.0-dev \
            pkg-config

      - name: Check Rust formatting
        run: |
          echo "Checking Rust code formatting..."
          cargo fmt --all -- --check

      - name: Run Clippy
        run: |
          echo "Running Clippy lints..."
          cargo clippy --all-targets --all-features -- -D warnings
